---
# # Setup/install tasks
# - include: setup-Debian.yml
#   when: ansible_os_family == 'Debian'

# Configure tasks
- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'

# - name: Ensure samba is started and enabled at boot
#   service: name=smbd state=started enabled=yes
