---
dependencies: []

galaxy_info:
  author: tehesfr
  description: Install Nginx reverse proxy.
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
      - jessie
    - name: Ubuntu
      versions:
      - xenial
      - trusty
  galaxy_tags:
    - web
    - security
    - proxy
