---
# Include variables and define needed variables
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Install MySQL
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure MySQL
- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'
