---
# Include variables and define needed variables
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Install PHP
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure PHP
- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Apache has selected state and enabled on boot
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: yes
