---
dependencies: []

galaxy_info:
  author: tehesfr
  description: Install Samba for Ubuntu/Debian.
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
      - jessie
    - name: Ubuntu
      versions:
      - xenial
      - trusty
  galaxy_tags:
    - share
