---

- name: upload cert for ssl site
  when: nginx_site_ssl_on
  template: src=site_cert.pem
        dest=/etc/ssl/certs/nginx-site-{{ nginx_site_name }}.pem
        mode=644
  notify:
    - restart nginx

- name: upload private key for ssl site
  when: nginx_site_ssl_on
  copy: src={{ nginx_site_key }}
        dest=/etc/ssl/private/nginx-site-{{ nginx_site_name }}.key
        mode=644
  notify:
    - restart nginx

- name: install site
  template: src=site.nginx.conf
            dest=/etc/nginx/sites-available/{{ nginx_site_name }}.conf
  notify:
    - restart nginx

- name: enable site
  file: src=/etc/nginx/sites-available/{{ nginx_site_name }}.conf
        dest=/etc/nginx/sites-enabled/{{ nginx_site_name }}.conf
        state=link
  notify:
    - restart nginx

- name: Remove default vhost in sites-enabled
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify:
    - restart nginx
