---
- name: Clone Drush {{ drush_version }} from GitHub
  git:
    repo: https://github.com/drush-ops/drush.git
    dest: "{{ drush_install_path }}"
    version: "{{ drush_version }}"
    update: "{{ drush_keep_updated }}"
    force: "{{ drush_force_update }}"
  register: drush_clone

- name: Check for composer.json
  stat: path={{ drush_install_path }}/composer.json
  register: drush_composer

- name: Install Drush dependencies with Composer
  shell: >
    cd {{ drush_install_path }} && composer update && composer install
  when: drush_clone.changed and drush_composer.stat.exists

- name: Create drush symlink
  file:
    src: "{{ drush_install_path }}/drush"
    dest: "{{ drush_path }}"
    state: link

- name: Run drush to finish setting it up
  command: "{{ drush_path }}"
  changed_when: false
